chore: create a npm-publish github actions workflow
philips-software/odin pull request #18
Opened 2020-11-15 13:21 UTC by mfklauberg

This PR introduces a workflow which aims to publish correctly the library code when a new [GitHub release](https://github.com/philips-software/odin/releases) is created.

The workflow is composed by two separate jobs, `build` and `publish-npm`. The `build` job will build, which also runs the linter in the code, and run the project test suite. After, the `publish-npm` job will run, with the main responsibility of publish the project to the [NPM registry](https://www.npmjs.com) under the [@odinjs/odin](https://www.npmjs.com/package/@odinjs/odin) scope.

If there's any more necessary steps, please let me know.

closes #4

2020-11-15 14:26 UTC, herberttn requested changes
I think it would be good to also change the node version on `.travis.yml`, so that the pull request checks use a matching version.

2020-11-15 14:26 UTC, herberttn commented on .github/workflows/npm-publish.yml
> +        run: yarn publish --access publich
```suggestion
        run: yarn publish --access public
```

2020-11-15 14:26 UTC, herberttn commented on .github/workflows/npm-publish.yml
> +# if everything is working correctly, it will try and publish the code the
Incomplete sentence

2020-11-16 16:53 UTC, herberttn approved these changes

2020-12-04 16:08 UTC, JeroenKnoops approved these changes

2021-01-12 21:33 UTC, herberttn requested changes

2021-01-12 21:33 UTC, herberttn commented on .travis.yml
> +- 14
Actually I think we can delete the Travis file, since we'll now be using Github Actions.

2021-01-13 07:59 UTC, JeroenKnoops commented
I've added the NPM_TOKEN in the secrets.. This will be published with user: philips-software-fa

2021-01-13 13:31 UTC, herberttn approved these changes

2021-01-13 13:32 UTC, herberttn commented
> I've added the NPM_TOKEN in the secrets.. This will be published with user: philips-software-fa

Thank you @JeroenKnoops!

2021-01-13 13:34 UTC, merged