Naming and deprecations
philips-software/odin pull request #53
Opened 2023-10-02 17:57 UTC by herberttn

- Adds `options.name` to `@Injectable` decorator with options.
- Adds deprecation messages to variations of decorators that will change or be removed in the future:
  - `@Injectable` with options will require an explicit `options.name`.
  - `@Injectable` without any arguments will be removed
  - `@Inject` with options will require an explicit `options.name`.
  - `@Inject` without any arguments will be removed
  - `@Inject` with a string will be removed
- Renames the package to `@philips-software/odin`
- Updates dependencies

2023-10-03 13:32 UTC, felipesilvino requested changes

2023-10-03 13:32 UTC, felipesilvino commented on README.md
I think `bundle.register(Injectable)` can also be deprecated. Therefore, we have two option for the snippet below.

1. Keep it as it is, it just points out the deprecation through a note.
2. Change it to already register using the `options` param along with the `class` name.

2023-10-03 13:32 UTC, felipesilvino commented on README.md
I think `bundle.register(Injectable)` can also be deprecated. Therefore, we have two option for the snippet below.

1. Keep it as it is, it just points out the deprecation through a note.
2. Change it to already register using the `options` param along with the `class` name.

2023-10-03 20:38 UTC, mfklauberg approved these changes

2023-10-04 11:50 UTC, felipesilvino approved these changes

2023-10-04 11:50 UTC, merged

2023-10-04 20:53 UTC, herberttn commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@philips-software/odin/v/3.0.0)
- [GitHub release](https://github.com/philips-software/odin/releases/tag/v3.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: